# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d903a9cbb259fcfbc8da5373e6a34ec55bdefc3f5a2becd754f3cd894a48e850216f683893e408573e2e765127bd659c02476bd63aad51187cf87dc209a9ba89

test:
  secret_key_base: 010420eab9ce8d58ed8e44488feb68a8b95a74635303e812dd0aa714c9e71b14b7149c42f4a4c8d79bd95bc7efa972468141fb2e1eff8025b6aea2501c31bd64

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
